name: svlint

on: [push, pull_request]

jobs:
  svlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install svlint
        run: |
          sudo snap install svlint --edge

      - name: Run svlint
        run: |
          svlint -v -f ${RGGEN_SV_RTL_ROOT}/compile.f
        env:
          RGGEN_SV_RTL_ROOT: ${{ github.workspace }}
